#### SETUP 01 LIBRARIES  ####
#### Library####

library("stringr")
library("stringi")
library("purrr")
library("tibble")
library("forcats")
library("ggplot2")
library("tidyr")
library("dplyr")
library("readr")
library(tidytext)
library(wordcloud2)
library(expss)
library(igraph)
library(ggraph)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
